config/routes.rb
Rails.application.routes.draw do
    mount ActionCable.server => '/cable'
    devise_for :users
    resources :rooms, only: [:index, :show]
    resources :messages, only: :create
    scope path: '/invites', controller: :invites do
        post 'search' => :search
        post 'create' => :create
        post 'accept' => :accept
    end
    root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :user
    belongs_to :friend, class_name: 'User'

    validates :user_id, :friend_id, presence: true

    after_create :send_message

    private

    def send_message
        ActionCable.server.broadcast "invites_#{self.friend_id}_channel", invite: self.id, user_id: self.friend_id, friendname: User.find(self.user_id).username
    end
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :room

    validates :user_id, :room_id, :body, presence: true
    validates :body, length: { minimum: 1 }

    after_create :send_message

    def timestamp
        created_at.strftime('%H:%M')
    end

    private
    
    def send_message
        ActionCable.server.broadcast "rooms_#{self.room_id}_channel", message: self.body, user: self.user.username, time: self.timestamp
    end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :roommates, dependent: :destroy
    has_many :users, through: :roommates
    has_many :messages, dependent: :destroy

    def with_user(user_id)
        self.roommates.where.not(user_id: user_id).first.user
    end

    def self.build(*users)
        Room.create.create_roommates(users) if Roommate.find_by(user_id: users[0], contact_id: users[1]).nil?
    end

    def create_roommates(users)
        users.each_with_index do |u, index|
            user = User.find(users[1 - index])
            self.roommates.create user_id: u, contact_id: users[1 - index]
            ActionCable.server.broadcast "users_#{u}_channel", username: user.username, email: Digest::MD5.hexdigest(user.email), room: self.id
        end
    end
end

app/models/roommate.rb
class Roommate < ApplicationRecord
    belongs_to :user
    belongs_to :room
    belongs_to :contact, class_name: 'User'

    validates :user_id, :room_id, :contact_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

    has_many :roommates, dependent: :destroy
    has_many :contacts, foreign_key: 'contact_id', class_name: 'Roommate'

    has_many :rooms, through: :roommates, dependent: :destroy
    
    has_many :messages, dependent: :destroy

    has_many :invitations, foreign_key: 'user_id', class_name: 'Invite', dependent: :destroy
    has_many :invites, foreign_key: 'friend_id'

    validates :username, presence: true
    validates :username, uniqueness: true, length: { in: 1..20 }

    scope :other_users, -> (user_id) { where.not(id: user_id).order(username: :asc) }

    def have_friend?(friend_id)
        self.contacts.find_by(user_id: friend_id).nil? ? false : true
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end

    private

    def get_access
        render template: 'welcome/index' unless current_user
    end

    def get_contacts_list
        @invites = current_user.invites
        @contacts = current_user.contacts
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
    before_action :get_access
    before_action :search_friend, only: :search
    before_action :search_invite, only: :accept

    def search
        @user = params[:user_id]
    end

    def create
        Invite.create user_id: params[:user_id], friend_id: params[:friend] if params[:user_id] && Invite.find_by(user_id: params[:user_id], friend_id: params[:friend]).nil?
    end

    def accept
        Room.build(@invite.user_id, @invite.friend_id) unless params[:accept].nil?
        @invite.destroy
    end

    private

    def search_friend
        @friend = User.find_by(username: params[:username])
        head :ok if @friend.nil? || current_user.have_friend?(@friend.id)
    end

    def search_invite
        @invite = Invite.find_by(id: params[:invite_id])
        head :ok if @invite.nil?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :get_access

    def create
        message = Message.create(message_params)
    end

    private
    
    def message_params
        params.require(:message).permit(:body, :room_id, :user_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :get_access
    before_action :get_contacts_list, except: :create
    before_action :get_room, only: :show

    def index
        
    end

    def show
        @messages = @room.messages.includes(:user).order(id: :asc)
        @contact = @room.with_user(current_user.id).username
    end

    private

    def get_room
        @room = current_user.rooms.find_by(id: params[:id])
        render template: 'shared/404', status: 404 if @room.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user_name, user_email, opts = {})
        opts[:alt] = user_name
        opts[:class] = 'gravatar'
        image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user_email)}?s=#{opts.delete(:size) { 30 }}",
              opts
    end
end

app/views/invites/accept.js.erb
$('#invite_<%= @invite.id %>').remove();

app/views/invites/search.js.erb
$('#searched').html('<p><%= @friend.username %><form class="create_button" action="/invites/create" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="user_id" id="user_id" value="<%= @user %>"><input type="hidden" name="friend" id="friend" value="<%= @friend.id %>"><input type="submit" class="submit" name="commit" value="" data-turbolinks="false"></form><form class="cancel_button" action="/invites/create" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="submit" class="submit" name="commit" value="" data-turbolinks="false"></form></p>');

app/views/layouts/application.html.slim
doctype html
html lang='en'
    head
        meta charset='utf-8'
        meta name='viewport' content='width=device-width, initial-scale=1.0'
        title == content_for?(:title) ? yield(:title) : 'Action Cable Chat'
        = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
        = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
        = csrf_meta_tag
        = action_cable_meta_tag
    body
        == yield

app/views/rooms/index.slim
- provide(:title, 'Величайший чат современности')
#chat_page
    = render 'shared/left_block'
    .right_block
        .container
            .row
                h2 Добро пожаловать!
                p Теперь вам следует выбрать собеседника, чтобы начать диалог с ним!

app/views/rooms/show.slim
- provide(:title, 'Беседка')
#chat_page
    = render 'shared/left_block'
    .right_block
        .header
            p= "Ваш собеседник - #{@contact}"
        .middle
            .row
                .small-12.columns
                    #messages data={ owner: "#{current_user.username}", room: "#{@room.id}" }
                        - current_name = ''
                        - @messages.map do |message|
                            .message class="#{message.user == current_user ? 'users' : 'roommates'}"
                                - if current_name != message.user.username
                                    - current_name = message.user.username
                                    p.author= current_name
                                .body
                                    span.time= message.timestamp
                                    .text= content_with_emoji(message.body)
        #new_message_block
            = form_for Message.new, remote: true do |f|
                = f.hidden_field :room_id, value: @room.id
                = f.hidden_field :user_id, value: current_user.id
                .medium-10.columns
                    p.emoji-picker-container
                        = f.text_field :body, class: 'form-control', label: false, placeholder: 'Сообщение', data: { emojiable: true }
                .medium-2.columns
                    = f.submit 'Отправить', class: 'button', data: { send: 'message' }

app/views/shared/404.slim
- provide(:title, 'Ошибка')
.right_block
    .container
        .row
            h2 Такой страницы не существует

app/views/shared/_left_block.slim
.left_block#user data={ owner: "#{current_user.id}" }
    header.block
        p#username
            = gravatar_for current_user.username, current_user.email
            = current_user.username
        = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'button', id: 'destroy'
    .search_block.block
        p.head Поиск контактов
        = form_tag('/invites/search', method: 'post', remote: true) do
            = hidden_field_tag :user_id, current_user.id
            = text_field_tag :username, nil, placeholder: 'Username'
            = submit_tag 'Найти', class: 'button', 'data-turbolinks': 'false'
        #searched
    .invites_block.block
        p.head Список приглашений
        - @invites.each do |invite|
            .invite id="invite_#{invite.id}"
                p= invite.user.username
                = form_tag('/invites/accept', method: 'post', remote: true, class: 'create_button') do
                    = hidden_field_tag :user_id, current_user.id
                    = hidden_field_tag :invite_id, invite.id
                    = hidden_field_tag :accept, true
                    = submit_tag '', class: 'submit', 'data-turbolinks': 'false'
                = form_tag('/invites/accept', method: 'post', remote: true, class: 'cancel_button') do
                    = hidden_field_tag :user_id, current_user.id
                    = hidden_field_tag :invite_id, invite.id
                    = submit_tag '', class: 'submit', 'data-turbolinks': 'false'
    .contacts_block.block
        p.head Список контактов
        - @contacts.each do |contact|
            - user = contact.user
            .contact class="#{'active' if @contact && @contact == user.username}"
                = gravatar_for user.username, user.email
                = link_to user.username, room_path(contact.room_id), 'data-turbolinks': 'false'

app/views/welcome/index.slim
- provide(:title, 'Welcome')
.inside
    .shadow
.container
    .row
        .small-12.small-6.small-offset-3.medium-4.medium-offset-8.columns
            .block#login
                .row
                    = simple_form_for(User.new, as: :user, url: session_path(:user)) do |f|
                        .small-12.columns
                            p= 'Авторизация'
                        .small-12.columns
                            = f.input :username, autofocus: true, label: false, placeholder: 'Имя пользователя'
                        .small-8.columns
                            = f.input :password, autocomplete: 'off', label: false, placeholder: 'Пароль'
                        .small-4.columns
                            = f.button :submit, 'Войти', class: 'button', id: 'authorization'
        .small-12.small-6.small-offset-3.medium-4.medium-offset-8.columns
            .block#signup
                .row
                    = simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f|
                        .small-12.columns
                            p= 'Регистрация'
                        .small-12.columns
                            = f.input :username, required: true, autofocus: true, label: false, placeholder: 'Имя пользователя'
                        .small-12.columns
                            = f.input :email, required: true, label: false, placeholder: 'Email'
                        .small-12.columns
                            = f.input :password, required: true, label: false, placeholder: 'Пароль'
                        .small-12.columns
                            = f.input :password_confirmation, autocomplete: 'off', required: true, label: false, placeholder: 'Подтверждение пароля'
                        .small-12.small-5.small-offset-7.columns
                            =  f.button :submit, 'Регистрация', class: 'button', id: 'registration'